services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    ports:
      - ${OLLAMA_PORT-11434}:11434
    environment:
      - CUDA_VISIBLE_DEVICES=2,3
      - COMPOSE_BAKE=TRUE
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-all}
              capabilities:
                - gpu

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    pull_policy: always
    volumes:
      - open-webui:/app/backend/data
      - ./data:/data
    depends_on:
      - ollama
      - chromadb
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - COMFYUI_BASE_URL=http://host.docker.internal:8188/
      - ENABLE_IMAGE_GENERATION=True
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - ENABLE_ADMIN_CHAT_ACCESS=false
      - COMPOSE_BAKE=TRUE
      # - VECTOR_DB=chroma
      # - CHROMA_HTTP_HOST=http://0.0.0.0:8000
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    pull_policy: always
    volumes:
      - ./chroma:/chroma/chroma
    network_mode: host
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
      - COMPOSE_BAKE=TRUE
    ports:
      - ${CHROMA_PORT-8000}:8000
    extra_hosts:
      - host.docker.internal:host-gateway

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    tty: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/ssl/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - open-webui
      - ollama

  # pipelines:
  #   image: ghcr.io/open-webui/pipelines:main
  #   container_name: pipelines
  #   pull_policy: always
  #   ports:
  #     - "9099:9099"
  #   volumes:
  #     - pipelines:/app/pipelines
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   networks:
  #     - app-network
  comfy_ui:
    init: true
    container_name: comfyui
    #  network_mode: "host"
    tty: true
    build:
      context: ./ComfyUI
      dockerfile: Dockerfile
    image: ghcr.io/kandapagari/comfyui:master
    restart: unless-stopped
    pull_policy: always
    volumes:
      - ./ComfyUI/models:/code/models
      - ./ComfyUI/custom_nodes:/code/custom_nodes
    ports:
      - 8188:8188
    environment:
      - CUDA_VISIBLE_DEVICES=2,3
      - CLI_ARGS=
      - COMPOSE_BAKE=TRUE
    security_opt:
      - "label=type:nvidia_container_t"
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-all}
              capabilities:
                - gpu
    entrypoint: [ "python", "main.py", "--listen" , "--enable-manager"]


volumes:
  ollama: {}
  open-webui: {}
  home: {}
  pipelines: {}
