services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    ports:
      - ${OLLAMA_PORT-11434}:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu
  
  # stable-diffusion-webui:
  #   image: emsi/stable-diffusion-webui
  #   build:
  #     context: ./stable-diffusion-webui/
  #     dockerfile: ./stable-diffusion-webui/Dockerfile
  #   ports:
  #     - "7860"
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #   volumes:
  #     - ./stable-diffusion-webui:/stable-diffusion-webui
  #     - home:/root
  #   command: python3 launch.py --listen
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: ${OLLAMA_GPU_DRIVER-nvidia}
  #             count: ${OLLAMA_GPU_COUNT-1}
  #             capabilities:
  #               - gpu
  

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      # - stable-diffusion-webui
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped


  comfy_ui:
    init: true
    container_name: comfyui
    network_mode: "host"
    tty: true
    build:
      context: ./ComfyUI
      dockerfile: Dockerfile
    volumes:
      - ./ComfyUI/models:/code/models
    ports:
      - 8188:8188
    environment:
      - CLI_ARGS=
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
    entrypoint: ["python", "main.py"]

volumes:
  ollama: {}
  open-webui: {}
  home: {}