services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    ports:
      - ${OLLAMA_PORT-11434}:11434
    environment:
      - CUDA_VISIBLE_DEVICES=0,1,2,3
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-all}
              capabilities:
                - gpu

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    pull_policy: always
    volumes:
      - open-webui:/app/backend/data
      - ./data:/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - COMFYUI_BASE_URL=http://host.docker.internal:7860/
      - ENABLE_IMAGE_GENERATION=True
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    pull_policy: always
    volumes:
      - ./chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - ${CHROMA_PORT-8000}:8000
    extra_hosts:
      - host.docker.internal:host-gateway


  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    pull_policy: always
    ports:
      - "9099:9099"
    volumes:
      - pipelines:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  # comfy_ui:
  #   init: true
  #   container_name: comfyui
  #   #  network_mode: "host"
  #   tty: true
  #   build:
  #     context: ./ComfyUI
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./ComfyUI/models:/code/models
  #   ports:
  #     - 7860:7860
  #   environment:
  #     - CLI_ARGS=
  #   security_opt:
  #     - "label=type:nvidia_container_t"
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             device_ids: [ "1" ]
  #             capabilities: [ gpu ]
  #   entrypoint: [ "python", "main.py", "--port=7860" ]


volumes:
  ollama: {}
  open-webui: {}
  home: {}
  pipelines: {}
